language: python
python:
      - "3.5"
install:
      - conda create -n image_extractor --file requirements.txt 
      - source activate image_extractor
      - python setup.py install
script: cd tests && python -m unittest -v
