language: python
python:
      - "3.5"
install:
      - sudo apt-get update
        # We do this conditionally because it saves us some downloading if the
        # version is the same.
      - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        fi
      - bash miniconda.sh -b -p $HOME/miniconda
      - export PATH="$HOME/miniconda/bin:$PATH"
      - hash -r
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda
        # Useful for debugging any issues with conda
      - conda info -a
        #get most recent dev version of ctapipe
      - git clone https://github.com/cta-observatory/ctapipe.git
      - cd ctapipe
      - git remote add upstream https://github.com/cta-observatory/ctapipe.git
      - git pull upstream master
      - conda env create -n image_extractor -f environment.yml
      - source activate image_extractor
      - conda install --yes --file requirements.txt
      - python setup.py install
script: cd tests && python -m unittest -v
